// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD469qxIMmZ7mnIXgH1lZ2vZCG4pE1EH2Q',
    appId: '1:93464380053:web:7ffb582b4eda66c3b8919c',
    messagingSenderId: '93464380053',
    projectId: 'donationproject-860df',
    authDomain: 'donationproject-860df.firebaseapp.com',
    storageBucket: 'donationproject-860df.appspot.com',
    measurementId: 'G-38FMMZB41S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcuBFOwE5eEZ7MhXxXohH3UTgt5L2M5j4',
    appId: '1:93464380053:android:ba8de7910c5aed59b8919c',
    messagingSenderId: '93464380053',
    projectId: 'donationproject-860df',
    storageBucket: 'donationproject-860df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8GfWVeUBMygSCJqwfWBUlSHMY6uFTgGg',
    appId: '1:93464380053:ios:5ee8b27d5c9b6fd8b8919c',
    messagingSenderId: '93464380053',
    projectId: 'donationproject-860df',
    storageBucket: 'donationproject-860df.appspot.com',
    iosClientId: '93464380053-17tgvoqtrvpgj4kkl116sgurmuqttt4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.donationproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8GfWVeUBMygSCJqwfWBUlSHMY6uFTgGg',
    appId: '1:93464380053:ios:5ee8b27d5c9b6fd8b8919c',
    messagingSenderId: '93464380053',
    projectId: 'donationproject-860df',
    storageBucket: 'donationproject-860df.appspot.com',
    iosClientId: '93464380053-17tgvoqtrvpgj4kkl116sgurmuqttt4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.donationproject',
  );
}
